### ISSUE TITLE
NTLM support?

### ISSUE THREAD

**Issue by tduccuong** [puzza007/katipo#113]
Hi,
sorry to ask this kind of question, but I did not find in your readme how to map between curl command and Erlang code, in particular is the support for NTLM authentication? My command is:

```
curl -H "<Header>" --ntlm --negotiate -u "<UserName>:<Password>" <URL> -XPOST --data-binary <BinaryContent>
```

How would I translate it into Katipo language?

Thanks a lot!

**Comment by puzza007** [comment]
Hi @tduccuong I have a branch with NTLM support here https://github.com/puzza007/katipo/pull/114. I've no way of testing it but using it would be something like

```erlang
    {ok, #{status := 200, body := Body}} =
        katipo:get(poolname, <<"https://example.com/foo">>,
                  #{http_auth => ntlm, userpwd => <<"domain\\user:passwor">>}).
```

If it works for you then I'll merge it and cut a release.
