### ISSUE TITLE
Publish new version to hex.pm

### ISSUE THREAD

**Issue by macasado86** [puzza007/katipo#150]
Hi @puzza007 ,

I was wondering if you could publish a new release to hex.pm repository. We are looking forward to using OTP 26 and we need the fix introduced in https://github.com/puzza007/katipo/pull/144

Thank you very much

**Comment by puzza007** [comment]
Hey @macasado86! Done https://hex.pm/packages/katipo/1.1.1. Let me know if you have any problems.
