### ISSUE TITLE
Erlang/OTP 20.0 compatibility

### ISSUE THREAD

**Issue by nroi** [puzza007/katipo#56]
Are there any plans to update this project to make it compatible with Erlang 20.0? Right now, it fails to build on my machine, and it seems due to changes introduced in Erlang versions more recent than 19.3. I played around with travis-ci, it builds fine with 19.3, but shows errors for 20.0: https://travis-ci.org/nroi/katipo

**Comment by puzza007** [comment]
Hi @nroi. Yeah I plan to bring it up to date. PRs welcome as well ;)

**Comment by puzza007** [comment]
Done in https://github.com/puzza007/katipo/pull/57. Let me know if you have any problems.
