### ISSUE TITLE
CURLOPT_INTERFACE

### ISSUE THREAD

**Issue by artemk** [puzza007/katipo#73]
is there any chance to add [CURLOPT_INTERFACE](https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html) option?

**Comment by puzza007** [comment]
Sure. I'll try and take a look this week.

**Comment by puzza007** [comment]
@artemk This [branch](https://github.com/puzza007/katipo/tree/curlopt-interface) should do what you want. Let me know if it works for you. I'll try and test it a bit more then merge.

**Comment by artemk** [comment]
@puzza007 thanks. looks and performing good. I will let you know about performing in production :)

**Comment by puzza007** [comment]
New release is https://hex.pm/packages/katipo/0.6.1

**Comment by artemk** [comment]
btw it works perfect in prod for 1year. Thanks.

**Comment by puzza007** [comment]
Great to hear. Thanks for the feedback!
